[package]
name = "zhiweave-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "zhiweave_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
notify.workspace = true
tauri.workspace = true
zhiweave-application = { path = "../../../crates/zhiweave-application" }
zhiweave-domain = { path = "../../../crates/zhiweave-domain" }
zhiweave-storage = { path = "../../../crates/zhiweave-storage" }

[lints]
workspace = true
