[package]
name = "zhiweave-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
atomic-write-file.workspace = true
fastcdc.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
uuid.workspace = true
zstd.workspace = true
zhiweave-application = { path = "../zhiweave-application" }
zhiweave-domain = { path = "../zhiweave-domain" }
zhiweave-markdown = { path = "../zhiweave-markdown" }

[lints]
workspace = true
